export const LOCATOR_TYPES = [
  { value: "label", label: "Label" },
  { value: "placeholder", label: "Placeholder" },
  { value: "css", label: "CSS Selector" },
  { value: "xpath", label: "XPath" },
  { value: "role", label: "Role" },
  { value: "testId", label: "Test ID" },
  { value: "text", label: "Text" },
  { value: "attribute", label: "Attribute (id/name/class)" },
];

export const MATCH_MODES = [
  { value: "contains", label: "Contains" },
  { value: "exact", label: "Exact" },
  { value: "regex", label: "Regular expression" },
];

export const ARIA_ROLES = [
  "textbox",
  "spinbutton",
  "checkbox",
  "radio",
  "combobox",
  "searchbox",
  "slider",
  "switch",
  "button",
];

export const DATA_TYPES = [
  { value: "static", label: "Static Value" },
  { value: "text", label: "Text (Lorem)" },
  { value: "alphanumeric", label: "Alphanumeric Template" },
  { value: "number", label: "Number" },
  { value: "date", label: "Date" },
  { value: "email", label: "Email" },
  { value: "firstName", label: "First Name" },
  { value: "middleName", label: "Middle Name" },
  { value: "lastName", label: "Last Name" },
  { value: "fullName", label: "Full Name" },
  { value: "username", label: "Username" },
  { value: "password", label: "Password" },
  { value: "telephone", label: "Telephone" },
  { value: "url", label: "URL" },
  { value: "organization", label: "Organization" },
  { value: "address", label: "Address" },
  { value: "city", label: "City" },
  { value: "state", label: "State / Region" },
  { value: "zip", label: "Postal / Zip Code" },
  { value: "country", label: "Country" },
  { value: "color", label: "Color" },
  { value: "list", label: "Randomized List" },
  { value: "regex", label: "Regular Expression" },
];

export const DEFAULT_SETTINGS = {
  fillPasswordMode: "random", // 'random' | 'fixed'
  fixedPasswordValue: "P@ssw0rd123",
  ignoreFieldsMatching: "",
  ignoreHiddenFields: true,
  ignoreFieldsWithValue: false,
  confirmationFieldsMatching: "confirm,repeat,verify",
  agreeTermsFieldsMatching: "agree,accept,terms,tos",
  matchAttributes: {
    id: true,
    name: true,
    label: true,
    ariaLabel: true,
    placeholder: true,
    className: false,
  },
  testIdAttribute: "data-testid",
  dispatchEvents: {
    input: true,
    change: true,
    blur: true,
  },
  defaultMaxLength: 100,
  enableContextMenu: true,
  enableSnippets: true,
  enableFillAnimation: true,
  enableFillSound: true,
};

export const DEFAULT_CUSTOM_FIELDS = [];

// Common-field presets, matched against id/name/class/aria-label/placeholder/label text combined
// (see locator-engine.js attributeString). Ordered so more specific patterns are checked first.
export const DEFAULT_FIELD_PRESETS = [
  {
    presetKey: "firstName",
    name: "First Name",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "first[\\s_-]*name|\\bfname\\b|\\bgivenname\\b",
    dataType: "firstName",
    dataOptions: {},
  },
  {
    presetKey: "middleName",
    name: "Middle Name",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "middle[\\s_-]*name|\\bmname\\b|middle[\\s_-]*initial",
    dataType: "middleName",
    dataOptions: {},
  },
  {
    presetKey: "lastName",
    name: "Last Name",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "last[\\s_-]*name|surname|\\blname\\b|family[\\s_-]*name",
    dataType: "lastName",
    dataOptions: {},
  },
  {
    presetKey: "fullName",
    name: "Full Name",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "full[\\s_-]*name|your[\\s_-]*name|\\bfullname\\b",
    dataType: "fullName",
    dataOptions: {},
  },
  {
    presetKey: "email",
    name: "Email",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "e[\\s_-]?mail",
    dataType: "email",
    dataOptions: {},
  },
  {
    presetKey: "phone",
    name: "Phone / Mobile",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "phone|mobile|\\btel\\b|contact[\\s_-]*number",
    dataType: "telephone",
    dataOptions: {},
  },
  {
    presetKey: "company",
    name: "Company / Organisation",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "compan(y|ies)|organi[sz]ation|business[\\s_-]*name",
    dataType: "organization",
    dataOptions: {},
  },
  {
    presetKey: "address",
    name: "Street Address",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "street|address([\\s_-]*(line)?[\\s_-]*1?)?\\b|addr1",
    dataType: "address",
    dataOptions: {},
  },
  {
    presetKey: "city",
    name: "City / Suburb",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "\\bcity\\b|\\bsuburb\\b|\\btown\\b",
    dataType: "city",
    dataOptions: {},
  },
  {
    presetKey: "state",
    name: "State / Region",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "\\bstate\\b|\\bregion\\b|province",
    dataType: "state",
    dataOptions: {},
  },
  {
    presetKey: "zip",
    name: "Postcode / Zip",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "post[\\s_-]*code|\\bzip\\b|postal[\\s_-]*code",
    dataType: "zip",
    dataOptions: {},
  },
  {
    presetKey: "country",
    name: "Country",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "\\bcountry\\b|\\bnation\\b",
    dataType: "country",
    dataOptions: {},
  },
  {
    presetKey: "username",
    name: "Username",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "user[\\s_-]*name|\\blogin\\b",
    dataType: "username",
    dataOptions: {},
  },
  {
    presetKey: "website",
    name: "Website",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "website|\\burl\\b|homepage",
    dataType: "url",
    dataOptions: {},
  },
  {
    presetKey: "dob",
    name: "Date of Birth",
    locatorType: "attribute",
    matchMode: "regex",
    matchValue: "date[\\s_-]*of[\\s_-]*birth|\\bdob\\b|birth[\\s_-]*date",
    dataType: "date",
    dataOptions: { minDays: -29200, maxDays: -6570 },
  },
];

export const DEFAULT_SNIPPETS = [];

export const STORAGE_KEYS = {
  settings: "ff_settings",
  customFields: "ff_customFields",
  snippets: "ff_snippets",
};
